env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'plugin:testing-library/recommended'
  - 'plugin:jest-dom/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - testing-library
  - jest-dom
rules: {
  "react/jsx-uses-react": "off",
  "react/react-in-jsx-scope": "off",
  "import/no-extraneous-dependencies": "off"
}
